# Generated by Django 5.1.2 on 2024-10-26 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('carnet', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('codMat', models.CharField(max_length=10)),
                ('seccion', models.IntegerField()),
            ],
        ),
    ]
