# Generated by Django 5.1.2 on 2024-10-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Escuela', models.CharField(max_length=50)),
                ('CodMat', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=100)),
                ('Docente', models.CharField(max_length=100)),
                ('CodEmp', models.CharField(blank=True, max_length=10, null=True)),
                ('Seccion', models.CharField(max_length=10)),
                ('Hora', models.CharField(max_length=20)),
                ('Dias', models.CharField(max_length=50)),
                ('Cupo', models.IntegerField()),
                ('Inscritos', models.IntegerField()),
                ('Aula', models.CharField(blank=True, max_length=50, null=True)),
                ('Estado', models.CharField(max_length=20)),
                ('Paralela', models.CharField(max_length=10)),
                ('Ciclo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CargaInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carnet', models.CharField(max_length=12)),
                ('CodMat', models.CharField(max_length=10)),
                ('Seccion', models.IntegerField()),
                ('CodInscripcion', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
